let plot_canvas = document.getElementById("plot_canvas");
let pen = plot_canvas.getContext("2d");
let f_canvas = document.getElementById("f_canvas");
let pencil = f_canvas.getContext("2d");
let structure_W = f_canvas.width;
let structure_H = f_canvas.height;
let left_padding = 50;
let down_padding = 0;
let min_x_value = -4;
let max_x_value = 4;
let min_y_value = -1;
let max_y_value = 1;
let max_weight = 2;
let weight_limit = 10;
let pixels_per_unit = 0.9*plot_canvas.height/(max_y_value-min_y_value);
let hor_pixels_per_unit = plot_canvas.width/(max_x_value-min_x_value);
let ver_pixels_per_unit = plot_canvas.height/(max_y_value-min_y_value);
let data_size = 10;
let f;
let data;
let current_error;